export const ARCHIVE_STATUS = {
  ALL: 'ALL',
  ACHIVED: 'ARCHIVE_STATUS_YES',
  UNACHIVED: 'ARCHIVE_STATUS_NO'
}

export const VERIFY_RESULTS = {
  ALL: 'ALL',
  PASS: 'OCR_STATUS_YES',
  PROCESSING: 'OCR_STATUS_PRO',
  FAIL: 'OCR_STATUS_NO'
}
