/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataPermissonForm: typeof import('./../components/PermiForm/DataPermissonForm.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ErrorPage: typeof import('./../components/ErrorPage/index.vue')['default']
    Icon: typeof import('./../components/Icon/index.vue')['default']
    MdEditor: typeof import('./../components/MdEditor/index.vue')['default']
    PermiListDialog: typeof import('./../components/PermiForm/PermiListDialog.vue')['default']
    Preview: typeof import('./../components/Preview/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryTitle: typeof import('./../components/SecondaryTitle/index.vue')['default']
    SideTree: typeof import('./../components/SideTree/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
